### ISSUE TITLE
Comments not showing to subscribed cards when you get notifications 

### ISSUE THREAD

**Issue by wilkobyl** [RARgames/4gaBoards#264]
When someone adds a comment to the card you are subscribed to and you get a notification to it, the new comment is not visible until refreshing page (when the notification disappear)
![17d84158f405a0dd.png](https://github.com/RARgames/4gaBoards/assets/40911978/a128543c-62ba-4200-aed1-f6dcf3a93e7a)

![17d8415a673aa38c.png](https://github.com/RARgames/4gaBoards/assets/40911978/f6e7618e-f09f-466e-a045-2a19c9456259)

**Comment by RARgames** [comment]
Cannot reproduce @wilkobyl

**Comment by RARgames** [comment]
BUG: 2nd person should be outside the board

**Comment by RARgames** [comment]
Should be fixed in [2d5ebd4](https://github.com/RARgames/4gaBoards/commit/2d5ebd48b1fb416724070629cbf46f52b9f8041d) - Please verify @wilkobyl

**Comment by wilkobyl** [comment]
generally fixed, the issue persist only when logging in and out to different account on the same tab (when I used the different tab the issue was gone and I could read the comments)

**Comment by RARgames** [comment]
Should be fully fixed now: [2038dbe](https://github.com/RARgames/4gaBoards/commit/2038dbe143ef3cb905b50b73edfecbd8b8e62ac7) - recheck @wilkobyl

**Comment by wilkobyl** [comment]
fixed
